# Assignment

Import numpy as np

In [1]:
import numpy as np

Make a python list => \[1,2,3,4,5\]

Convert it into numpy array and print it

In [3]:
list1 = [1,2,3,4,5]
np.array(list1)

array([1, 2, 3, 4, 5])

Make a python matrix (3 x 3) => \[[1,2,3],[4,5,6],[7,8,9]\]

Convert it into numpy array and print it

In [4]:
matrix1 = [[1,2,3],[4,5,6],[7,8,9]]
np.array(matrix1)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Make a matrix (3 x 3) using built-in methods (like arange(), reshape() etc.):

\[ [1,3,5],

 [7,9,11],
 
 [13,15,17] \]

In [5]:
arr2 = np.arange(1,19,2) # does not consider the last element or value
arr2.reshape(3,3)

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

Create a numpy array with 10 random numbers from 0 to 10 (there should be few numbers greater than 1)

In [7]:
arr3 = np.random.randn(10)
arr3

array([-0.21018049,  2.44756364, -1.15507536, -0.52912029,  0.36448852,
        0.36441865, -1.4346832 , -1.05009222,  0.77984683,  1.07404423])

Create numpy array => \[1,2,3,4,5\] and convert it to 2D array with 5 rows

In [8]:
list4 = [1,2,3,4,5]
arr4 = np.array(list4)
arr4.reshape(5,1)

array([[1],
       [2],
       [3],
       [4],
       [5]])

Print the shape of the above created array

In [9]:
arr4.shape

(5,)

Create a numpy array with 10 elements in it. Access and print its 3rd, 4th and 9th element.

In [10]:
list6 = [1,2,3,4,5,6,7,8,9,10]
print(list6)
arr5 = np.array(list6)
print(arr5[2],arr5[3],arr5[8]) # takes the values under the index 3,4, and 9 

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
3 4 9


Print alternate elements of that array

In [11]:
arr6 = arr5[::2]
arr6

array([1, 3, 5, 7, 9])

Change last 3 elements into 100 using broadcasting and print

In [12]:
# broadcasting
arr6[-3:]=100
arr6

array([  1,   3, 100, 100, 100])

Create a 5 x 5 matrix (fill it with any element you like), print it.

Then print the middle (3 x 3) matrix.

In [13]:
matrix2 = np.arange(25).reshape(5, 5)
print(matrix2)
print('Mid 3X3 matrix:',matrix2[1:4,1:4],sep='\n')

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
Mid 3X3 matrix:
[[ 6  7  8]
 [11 12 13]
 [16 17 18]]
